SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Models/Siniflar/Sinema.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SinemaBiletOtomasyonu.Models.Siniflar
{
    public class Sinema
    {
        [Key]
        public int SinemaID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string SinemaAdi { get; set; }

        public int? Plaka { get; set; }
        public bool IsChecked { get; set; }

        public virtual Sehir Sehir { get; set; }


        //public ICollection<SinemaSalon> SinemaSalons { get; set; }


        //public ICollection<FilmSinema> FilmSinemas { get; set; }

        public ICollection<Salon> Salons { get; set; }

        public ICollection<FilmSalonSinema> FilmSalonSinemas { get; set; }



    }
}

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Controllers/SinemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SinemaBiletOtomasyonu.Models.Siniflar;

namespace SinemaBiletOtomasyonu.Controllers
{
    public class SinemaController : Controller
    {
        Context c = new Context();

        // GET: Sinema
        public ActionResult Index(string option, string search, int page = 1)
        {
            if (option == "SinemaAdi")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(c.Sinemas.Where(x => x.SinemaAdi.ToString() == search || search == null).ToList().ToPagedList(page, 10));
            }
            else if (option == "Sehir.SehirAdi")
            {
                return View(c.Sinemas.Where(x => x.Sehir.SehirAdi == search || search == null).ToList().ToPagedList(page, 10));

            }
            else
            {
                return View(c.Sinemas.ToList().ToPagedList(page, 10));

            }
        }

        [HttpGet]
        public ActionResult SinemaEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Sehirs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.SehirAdi,
                                               Value = x.Plaka.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
        [HttpPost]
        public ActionResult SinemaEkle(Sinema s)
        {
            c.Sinemas.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SinemaSil(int id)
        {
            var tur = c.Sinemas.Find(id);
            c.Sinemas.Remove(tur);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SinemaGetir(int id)
        {


            List<SelectListItem> deger1 = (from x in c.Sehirs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.SehirAdi,
                                               Value = x.Plaka.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            var flm = c.Sinemas.Find(id);
            return View("SinemaGetir", flm);
        }
        public ActionResult SinemaGuncelle(Sinema s)
        {
            
            var fl = c.Sinemas.Find(s.SinemaID);
            fl.SinemaAdi = s.SinemaAdi;
            fl.Plaka = s.Plaka;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

       
    }
}

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Sinema/Index.cshtml
@using SinemaBiletOtomasyonu.Models.Siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Sinema>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Index", "Sinema", FormMethod.Get))
{

    <b> Arama Seçeneği: </b>@Html.RadioButton("option", "SinemaAdi") <text>Sinema Adı</text>
    @Html.RadioButton("option", "Sehir.SehirAdi") <text> Şehir </text>
    @Html.RadioButton("option", "Tumu") <text>Tümü</text>
    @Html.TextBox("search")
    <input type="submit"
           name="submit"
           value="Search" />

    <table class="table table-bordered" style="margin:20px">

        <tr>
            <th>Sinema ID</th>
            <th>Sinema Adı</th>
            <th>Şehir</th>
            <th>Salonlar</th>
            <th>Sil</th>
            <th>Güncelle</th>

        </tr>

        @foreach (var k in Model)
        {

            <tr>
                <td>
                    @k.SinemaID
                </td>
                <td>
                    @k.SinemaAdi
                </td>

                <td>
                    @k.Sehir.SehirAdi
                </td>
                <td>
                </td>


                <td> <a href="/Sinema/SinemaSil/@k.SinemaID" class="btn btn-danger"><font color="white">Sil</font></a></td>
                <td> <a href="/Sinema/SinemaGetir/@k.SinemaID" class="btn btn-warning"><font color="white">Güncelle</font></a></td>
                @*<td> <a href="/Departman/DepartmanPersonelSatis/@k.Personelid" class="btn btn-default" style="background-color:burlywood; color:white;">Detaylar</a></td>*@

            </tr>
        }
    </table>
    <a href="/Sinema/SinemaEkle" class="btn btn-info">Sinema Ekle</a>
}

@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
<br />
<br />


SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Sinema/SinemaEkle.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Sinema

@{
    ViewBag.Title = "SinemaEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Film Ekle</h2>
<br />

@using (Html.BeginForm("SinemaEkle", "Sinema", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<table>
    <tr>
        <td>@Html.LabelFor(x => x.SinemaAdi)</td>
        <td>
            @Html.TextBoxFor(x => x.SinemaAdi,
            new { @class = "form-kontrol" })
        </td>
    </tr>
    <tr>
        <td> @Html.LabelFor(x => x.Sehir)</td>
        <td> @Html.DropDownListFor(x => x.Plaka, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control", @style = "width: 185px;" })</td>
    </tr>
    

</table>
    <button class="btn btn-info">Ekle</button>

}



SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Sinema/SinemaGetir.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Sinema

@{
    ViewBag.Title = "SinemaGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Sinema Güncelleme Sayfası</h2>
@using (Html.BeginForm("SinemaGuncelle", "Sinema", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.SinemaID);
        @Html.LabelFor(x => x.SinemaAdi)
        @Html.TextBoxFor(x => x.SinemaAdi,
        new { @class = "form-kontrol" })
        <br />
        @Html.LabelFor(x => x.Sehir)
        @Html.DropDownListFor(x => x.Plaka, (List<SelectListItem>)ViewBag.dgr1, new
        {
            @class = "form-control"
        })
       
        <button class="btn btn-info">Güncelle</button>


    </div>


}


