SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Models/Siniflar/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SinemaBiletOtomasyonu.Models.Siniflar
{
    public class Film
    {
        [Key]
        public int FilmID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string FilmAdi { get; set; }
        public int FilmSuresi { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(300)]
        public string Afis { get; set; }
        public double Fiyat { get; set; }

        public int TurID { get; set; }

        [Column(TypeName = "Varchar")]
        [MaxLength]
        public string KisaAciklama { get; set; }

        [Column(TypeName = "text")]
        [MaxLength]
        [AllowHtml]
        public string Aciklama { get; set; }
      
        public virtual FilmTur FilmTur { get; set; }
        //public ICollection<Bilet> Bilets { get; set; }
        //public ICollection<FilmSinema> FilmSinemas { get; set; }

       
        public ICollection<FilmSalonSinema> FilmSalonSinemas { get; set; }



    }
}

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SinemaBiletOtomasyonu.Models.Siniflar;

namespace SinemaBiletOtomasyonu.Controllers
{
    public class FilmController : Controller
    {
        Context c = new Context();
        // GET: Film
        public ActionResult Index(string option, string search, int page = 1) /*admin görünecek kısım*/
        {
            if (option == "FilmAdi")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(c.Films.Where(x => x.FilmAdi == search || search == null).ToList().ToPagedList(page, 10));
            }
            else if (option == "FilmTur.TurAdi")
            {
                return View(c.Films.Where(x => x.FilmTur.TurAdi == search || search == null).ToList().ToPagedList(page, 10));

            }
            else
            {
                return View(c.Films.ToList().ToPagedList(page, 10));

            }
        }
        public ActionResult Index2() /*Admin panelinde görünecek kısım*/
        {
            var degerler = c.Films.ToList();
            return View(degerler);
        }
        //[HttpPost]
        //public JsonResult UploadFile(HttpPostedFileBase uploadedFiles)
        //{
        //    string returnImagePath = string.Empty;
        //    string fileName;
        //    string Extension;
        //    string imageName;
        //    string imageSavePath;

        //    if (uploadedFiles.ContentLength > 0)
        //    {
        //        fileName = Path.GetFileNameWithoutExtension(uploadedFiles.FileName);
        //        Extension = Path.GetExtension(uploadedFiles.FileName);
        //        imageName = fileName + DateTime.Now.ToString("yyyyMMddHHmmss");
        //        imageSavePath = Server.MapPath("/images/") + imageName + Extension;

        //        uploadedFiles.SaveAs(imageSavePath);
        //        returnImagePath = "/images/" + imageName + Extension;
        //    }

        //    return Json(Convert.ToString(returnImagePath), JsonRequestBehavior.AllowGet);
        //}
        [Authorize]
        [HttpGet]
        public ActionResult FilmEkle()
        {
            List<SelectListItem> deger1 = (from x in c.FilmTurs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.TurAdi,
                                               Value = x.TurID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult FilmEkle(Film f)
        {

            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/images/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                f.Afis = "/images/" + dosyaadi + uzanti;
            }
            c.Films.Add(f);
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult FilmSil(int id)
        {
            var tur = c.Films.Find(id);
            c.Films.Remove(tur);
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult FilmGetir(int id)
        {


            List<SelectListItem> deger1 = (from x in c.FilmTurs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.TurAdi,
                                               Value = x.TurID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            var flm = c.Films.Find(id);

            var dgr2 = c.Films.Find(id);
            ViewBag.dgr2 = dgr2.Afis;
            return View("FilmGetir", flm);
        }
        public ActionResult FilmGuncelle(Film k)
        {
            if (!ModelState.IsValid)
            {
                return View("FilmGetir");
            }
            try
            {
                if (Request.Files.Count > 0)
                {
                    string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);
                    string yol = "~/images/" + dosyaadi + uzanti;
                    Request.Files[0].SaveAs(Server.MapPath(yol));
                    k.Afis = "/images/" + dosyaadi + uzanti;
                }
            }
            catch (System.IO.DirectoryNotFoundException)
            {
                var f = c.Films.Find(k.FilmID);
                f.FilmAdi = k.FilmAdi;
                f.FilmSuresi = k.FilmSuresi;
                f.TurID = k.TurID;
                f.Fiyat = k.Fiyat;
                f.Afis = k.Afis;
                f.KisaAciklama = k.KisaAciklama;
                f.Aciklama = k.Aciklama;
                c.SaveChanges();
                return RedirectToAction("Index");
            }
            var fl = c.Films.Find(k.FilmID);
            fl.FilmAdi = k.FilmAdi;
            fl.FilmSuresi = k.FilmSuresi;
            fl.TurID = k.TurID;
            fl.Fiyat = k.Fiyat;
            fl.Afis = k.Afis;
            fl.KisaAciklama = k.KisaAciklama;
            fl.Aciklama = k.Aciklama;
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public PartialViewResult Partial1()
        {
            var sorgu = c.Salons.ToList();
            return PartialView(sorgu);
        }
    }
}

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Film/FilmEkle.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Film
@{
    ViewBag.Title = "FilmEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("FilmEkle", "Film", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>@Html.LabelFor(x => x.FilmAdi)</td>
            <td>
                @Html.TextBoxFor(x => x.FilmAdi,
                new { @class = "form-kontrol" })
            </td>
        </tr>
        <tr>
            <td> @Html.LabelFor(x => x.FilmTur)</td>
            <td> @Html.DropDownListFor(x => x.TurID, (List<SelectListItem>)ViewBag.dgr1,
                new { @class = "form-control", @style = "width: 185px;" })</td>
        </tr>
        <tr>
            <td> @Html.LabelFor(x => x.FilmSuresi)</td>
            <td>
                @Html.TextBoxFor(x => x.FilmSuresi,
                new { @class = "form-kontrol" })
            </td>
        </tr>
        <tr>
            <td> @Html.LabelFor(x => x.Fiyat)</td>
            <td>
                @Html.TextBoxFor(x => x.Fiyat,
                    new { @class = "form-kontrol" })
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(x => x.Aciklama)</td>
            <td>
                @Html.TextBoxFor(x => x.Aciklama,
                new { @class = "form-kontrol" })
            </td>
        </tr>
        <tr>
            <td> <label><b> Film Afişi </b></label></td>
            <td> <input type="file" name="Afis" /></td>
        </tr>
    </table>
    <button class="btn btn-info">Ekle</button>""
}





<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>


<!-- include libraries(jQuery, bootstrap) -->
@*<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@

<script>
    $('#summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 500,

        //callbacks: {
        //    onImageUpload: function (files) {
        //        for (var i = 0; i < files.length; i++) {

        //            uploadImage(files[i]);
        //        }
        //    }
        //},
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });
    function uploadImage(file) {
        var formData = new FormData();
        formData.append("uploadedFiles", file);
        $.ajax({
            data: formData,
            type: "POST",
            url: '/Post/UploadFile',
            cache: false,
            contentType: false,

            processData: false,
            success: function (FileUrl) {
                alert(FileUrl);
                var imgNode = document.createElement('img');
                imgNode.src = FileUrl;
                $('#summernote').summernote('insertNode', imgNode);
            },
            error: function (data) {
                alert(data.responseText);
            }
        });
    }



</script>

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Film/FilmGetir.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Film
@{
    ViewBag.Title = "FilmGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Film Güncelleme Sayfası</h2>
@using (Html.BeginForm("FilmGuncelle", "Film", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<table>
    <div class="form-group">
        @Html.HiddenFor(x => x.FilmID)
        <tr>
            <td> @Html.LabelFor(x => x.FilmAdi)</td>
            <td>
                @Html.TextBoxFor(x => x.FilmAdi,
            new { @class = "form-kontrol" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(x => x.FilmTur)
            </td>
            <td>
                @Html.DropDownListFor(x => x.TurID, (List<SelectListItem>)ViewBag.dgr1, new
           {
               @class = "form-control",
               @style = "width: 185px;"
           })
            </td>
        </tr>
        <br />
        <tr>
            <td>
                @Html.LabelFor(x => x.FilmSuresi)
            </td>
            <td>
                @Html.TextBoxFor(x => x.FilmSuresi,
            new { @class = "form-kontrol" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(x => x.Fiyat)
            </td>
            <td>
                @Html.TextBoxFor(x => x.Fiyat,
            new { @class = "form-kontrol" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Kısa Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
            </td>
            <td>
                @Html.EditorFor(model => model.KisaAciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KisaAciklama, "", new { @class = "text-danger" })

            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
            </td>
            <td>
                @Html.TextAreaFor(m => m.Aciklama, new { @id = "summernote" })

            </td>
        </tr>
        <tr>
            <td>
                <label><b>Film Afişi</b></label>
            </td>
            <td>
                <input type="file" name="Afis" class="btn btn-success" style="width:185px;" />

                <input type="text" name="Afis" value="@ViewBag.dgr2" class="form-control" style="width:185px;" readonly />
            </td>
            @*@Html.ValidationMessageFor(x => x.Afis, "", new { @style = "color:red" })*@
            @*@@Html.TextBoxFor(m => m.PersonelGorsel, new { @class = "form-control" })@*@

        </tr>

    </div>
</table>
<button class="btn btn-info">Güncelle</button>


}




<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>


<!-- include libraries(jQuery, bootstrap) -->
@*<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@

<script>
    $('#summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 500,

        //callbacks: {
        //    onImageUpload: function (files) {
        //        for (var i = 0; i < files.length; i++) {

        //            uploadImage(files[i]);
        //        }
        //    }
        //},
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });
    function uploadImage(file) {
        var formData = new FormData();
        formData.append("uploadedFiles", file);
        $.ajax({
            data: formData,
            type: "POST",
            url: '/Post/UploadFile',
            cache: false,
            contentType: false,

            processData: false,
            success: function (FileUrl) {
                alert(FileUrl);
                var imgNode = document.createElement('img');
                imgNode.src = FileUrl;
                $('#summernote').summernote('insertNode', imgNode);
            },
            error: function (data) {
                alert(data.responseText);
            }
        });
    }



</script>

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Film/Index.cshtml
@using SinemaBiletOtomasyonu.Models.Siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Film>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Filmler</h2>

@using (Html.BeginForm("Index", "Film", FormMethod.Get))
{

    <b> Arama Seçeneği: </b>@Html.RadioButton("option", "FilmAdi") <text>Film Adı</text>
    @Html.RadioButton("option", "FilmTur.TurAdi") <text> Tür </text>
    @Html.RadioButton("option", "Tumu") <text>Tümü</text>
    @Html.TextBox("search")
    <input type="submit"
           name="submit"
           value="Search" />

    <table class="table table-bordered" style="margin:20px">

        <tr>
            <th>Film ID</th>
            <th>Film Adı</th>
            <th>Süresi</th>
            <th>Tür</th>
            <th>Fiyat</th>
            <th>Açıklama</th>
            <th>Afiş</th>
            <th>Sil</th>
            <th>Güncelle</th>

        </tr>

        @foreach (var k in Model)
        {

            <tr>
                <td>
                    @k.FilmID
                </td>
                <td>
                    @k.FilmAdi
                </td>
                <td>
                    @k.FilmSuresi
                </td>
                <td>
                    @k.FilmTur.TurAdi
                </td>
                <td>
                    @k.Fiyat
                </td>
                <td>
                    @k.Aciklama.Substring(0, 5)
                </td>
                <td>
                    <img src="@k.Afis" width="50px" height="50px"
                         onclick="this.src = '@k.Afis'; this.height = 150; this.width = 150;0"
                         ondblclick="this.src='@k.Afis'; this.width=150; this.height=150;" />
                </td>
                <td> <a href="/Film/FilmSil/@k.FilmID" class="btn btn-danger"><font color="white">Sil</font></a></td>
                <td> <a href="/Film/FilmGetir/@k.FilmID" class="btn btn-warning"><font color="white">Güncelle</font></a></td>
                @*<td> <a href="/Departman/DepartmanPersonelSatis/@k.Personelid" class="btn btn-default" style="background-color:burlywood; color:white;">Detaylar</a></td>*@

            </tr>
        }
    </table>
    <a href="/Film/FilmEkle" class="btn btn-info">Film Ekle</a>
}
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))

<br />
<br />


SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Film/Partial1.cshtml
@*@using SinemaBiletOtomasyonu.Models.Siniflar
@model List<Sinema>



@foreach (var item in Model)
{
    <div class="checkbox">
        <label>
            <input type="checkbox"
                   name="SelectedFruits"
                   value="@item.SinemaID"
                   @if (item.IsChecked.Contains(item.SinemaID)) { <text> checked </text> } /> @item.SinemaAdi
            </label>
        </div>
    }*@