SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Controllers/BiletDetayController.cs
using SinemaBiletOtomasyonu.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SinemaBiletOtomasyonu.Controllers
{
    public class BiletDetayController : Controller
    {
        // GET: BiletDetay
        Context c = new Context();
     
        public ActionResult Index()
        {
            
            var degerler = c.Koltuks.ToList();
            return View(degerler);

            //Class2 cs = new Class2();
            //cs.Deger6 = c.Koltuks.Where(x => x.KoltukID == id).ToList();
            //cs.Deger3 = c.Salons.Where(x => x == id).ToList();
            //cs.Deger4 = c.Sinemas.Where(x => x.FilmSalonSinemas == id).ToList();
            //cs.Deger5 = c.Films.Where(x => x.FilmSalonSinemas == id).ToList();

            //return View(cs);
        }

        public PartialViewResult Partial4()
        {

            List<SelectListItem> deger1 = (from x in c.Sinemas.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.SinemaAdi,
                                               Value = x.SinemaID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            return PartialView("Partial4");
        }
        public PartialViewResult Partial5()
        {

            List<SelectListItem> deger1 = (from x in c.Salons.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.SalonAdi,
                                               Value = x.SalonID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            return PartialView("Partial5");
        }
        public PartialViewResult Partial6()
        {

            List<SelectListItem> deger1 = (from x in c.Seans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Saat.ToString(),
                                               Value = x.SeansID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            return PartialView("Partial6");
        }
        public PartialViewResult Partial7()
        {

            List<SelectListItem> deger1 = (from x in c.Films.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.FilmAdi.ToString(),
                                               Value = x.FilmID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            return PartialView("Partial7");
        }

    }
}

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/BiletDetay/Index.cshtml
@using SinemaBiletOtomasyonu.Models.Siniflar
@model List<Koltuk>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AnaLayout.cshtml";
}

<div class="container" align="center">

    <img src="~/images/perde.jpg" width="1100px" height="400px" />
    <table class="table table-light border">
        <tr>
            @foreach (var x in Model)
            {

                <td class="btn btn-success m-1 text-dark btn btn-sm">@x.KoltukAdi</td>
            }

        </tr>
        <tr>
            <td>
                @Html.Action("Partial7", "BiletDetay")
            </td>
        </tr>
        <tr>
            <td>
                @Html.Action("Partial4", "BiletDetay")
            </td>
        </tr>
        <tr>
            <td>
                @Html.Action("Partial5", "BiletDetay")
            </td>
        </tr>
        <tr>
            <td>
                @Html.Action("Partial6", "BiletDetay")
            </td>
        </tr>


    </table>
    <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#exampleModal">Ödeme Adımına Geç</button>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-xxl-down">
        <div class="modal-content">
            <div class="modal-header  text-center">
                <h3 class="modal-title w-100" id="exampleModalLabel">
                    Ödeme Yap</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" align="center">

                <div class="container mt-3 mb-3">
                    <div class="d-flex justify-content-between align-items-center mb-5">
                        <div class="d-flex flex-row align-items-center">
                            <h4 class="text-uppercase mt-1">SinemaDevi</h4> <span class="ml-2">Ödeme</span>
                        </div> <a href="index.html" class="cancel com-color">Anasayfaya dön</a>
                    </div>
                    <div class="row">
                        <div class="col-md-6">

                            <div class="about">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex flex-row mt-1">

                                    </div>

                                </div>
                                <p>Film öncesinde bilet kontrolü yapılacağı için lütfen film başlamadan en az 10 dk önce salonda bulununuz. Diğer izleyicilerimizin seyir keyfinin bozulmaması açısından film başladıktan sonra salona girmemeye özen gösterelim. İyi seyirler</p>
                                <div class="p-2 d-flex justify-content-between bg-pay align-items-center"> <span>7. Koğuştaki Mucize</span> <span>13:30</span> </div>
                                <hr>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="d-flex flex-row mt-1">
                                        <h6>Toplam Tutar</h6>
                                        <h6 class="text-success font-weight-bold ml-1">47.15₺</h6>
                                    </div>
                                    <div class="d-flex flex-row align-items-center com-color"> <i class="fa fa-plus-circle"></i> <span class="ml-1">Kart Ekle</span> </div>
                                </div>
                                <p>Verified by Visa ve MasterCard SecureCode logoları bulunan sanal işyerlerinden yapılan online alışverişler Visa ve MasterCard güvencesi altındadır.</p>
                                <div class="d-flex flex-column">
                                    <label class="radio">
                                        <input type="radio" name="gender" value="MALE" checked>
                                        <div class="d-flex justify-content-between"> <span>VISA</span> <span>**** 5645</span> </div>
                                    </label> <label class="radio">
                                        <input type="radio" name="gender" value="FEMALE">
                                        <div class="d-flex justify-content-between"> <span>MASTER CARD</span> <span>**** 5069</span> </div>
                                    </label>
                                </div>
                                <div class="buttons"> <button class="btn btn-success btn-block">Ödeme Yap</button> </div>
                            </div>
                        </div>
                        <div class="col-md-2"> </div>
                        <div class="col-md-4">
                            <div class="bg-pay p-3">
                                <span class="font-weight-bold">Sipariş Özeti</span>

                                <hr>
                                <div class="d-flex justify-content-between mt-2"> <span class="lh-16 fw-500">7. Koşuştaki Mucize </span> <span>Salon-5</span> </div>
                                <div class="d-flex justify-content-between mt-2"> <span class="lh-16 fw-500">13:30</span> <span>Koltuk K-15 K-17</span> </div>
                                <hr>
                                <div class="d-flex justify-content-between mt-2"> <span class="fw-500">Bilet Tutarı</span> <span>40₺</span> </div>
                                <div class="d-flex justify-content-between mt-2"> <span class="fw-500">İndirim</span> <span>0.0₺</span> </div>
                                <div class="d-flex justify-content-between mt-2"> <span class="fw-500">İndirim Yüzdesi(0%)</span> <span>$0.0₺</span> </div>
                                <div class="d-flex justify-content-between mt-2"> <span class="fw-500">KDV(18%) </span> <span>7.15₺</span> </div>

                                <hr>
                                <div class="d-flex justify-content-between mt-2"> <span class="fw-500">Toplam </span> <span class="text-success">47.15₺</span> </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <div class="col text-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Çıkış</button>
                    <button type="button" class="btn btn-dark">Öde</button>
                </div>
            </div>
        </div>
    </div>
</div>

<br />

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/BiletDetay/Partial4.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Sinema

<div class="col-3">
    <label class="labels">Sinema Seçiniz</label>
    @Html.DropDownListFor(x => x.SinemaID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
</div>

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/BiletDetay/Partial5.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Salon

<div class="col-3">
    <label class="labels">Salon Seçiniz</label>
    @Html.DropDownListFor(x => x.SalonID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
</div>

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/BiletDetay/Partial6.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Seans

<div class="col-3">
    <label class="labels">Seans Seçiniz</label>
    @Html.DropDownListFor(x => x.SeansID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
</div>


SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/BiletDetay/Partial7.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Film

<div class="col-3">
    <label class="labels">Seans Seçiniz</label>
    @Html.DropDownListFor(x => x.FilmID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
</div>
