SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Models/Siniflar/Haber.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace SinemaBiletOtomasyonu.Models.Siniflar
{
    public class Haber
    {
        public long id { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Title { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Metatitle { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(300)]
        public string KucukResim { get; set; }

        [Column(TypeName = "Varchar")]
        [MaxLength]
        public string Shortinfo { get; set; }
        [Column(TypeName = "text")]
        [MaxLength]
        [AllowHtml]
        public string İcerik { get; set; }
        public DateTime? PostedDate { get; set; }
        public bool Active { get; set; }

    }
}

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Controllers/HaberController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SinemaBiletOtomasyonu.Models.Siniflar;
using PagedList;

namespace SinemaBiletOtomasyonu.Controllers
{
    public class HaberController : Controller
    {
        Context c = new Context();
        // GET: Haber
        public ActionResult Index(int page = 1) //Anasayfa
        {
            var degerler = c.Habers.ToList().ToPagedList(page, 12);
            return View(degerler);
        }
        [Authorize]
        public ActionResult Index2(string option, string search, int page = 1) //Admin
        {

            if (option == "id")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(c.Habers.Where(x => x.id.ToString() == search || search == null).ToList().ToPagedList(page, 10));
            }
            else if (option == "PostedDate")
            {
                return View(c.Habers.Where(x => x.PostedDate.ToString() == search || search == null).ToList().ToPagedList(page, 10));

            }
            else if (option == "Title")
            {
                return View(c.Habers.Where(x => x.Title.ToString() == search || search == null).ToList().ToPagedList(page, 10));

            }
            else
            {
                return View(c.Habers.ToList().ToPagedList(page, 10));

            }
        }

        [HttpPost]
        public JsonResult UploadFile(HttpPostedFileBase uploadedFiles)
        {
            string returnImagePath = string.Empty;
            string fileName;
            string Extension;
            string imageName;
            string imageSavePath;

            if (uploadedFiles.ContentLength > 0)
            {
                fileName = Path.GetFileNameWithoutExtension(uploadedFiles.FileName);
                Extension = Path.GetExtension(uploadedFiles.FileName);
                imageName = fileName + DateTime.Now.ToString("yyyyMMddHHmmss");
                imageSavePath = Server.MapPath("/postedImage/") + imageName + Extension;

                uploadedFiles.SaveAs(imageSavePath);
                returnImagePath = "/postedImage/" + imageName + Extension;
            }

            return Json(Convert.ToString(returnImagePath), JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public ActionResult YeniHaber()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult YeniHaber(Haber hbr)
        {

            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/images/" + dosyaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                hbr.KucukResim = "/images/" + dosyaadi + uzanti;
            }

            c.Habers.Add(hbr);
            c.SaveChanges();
            return View();

        }

        public ActionResult HaberSil(int id)
        {
            var tur = c.Habers.Find(id);
            c.Habers.Remove(tur);
            c.SaveChanges();
            return RedirectToAction("Index2");
        }

        public ActionResult HaberGetir(int id)
        {

            var flm = c.Habers.Find(id);

            var dgr2 = c.Habers.Find(id);
            ViewBag.dgr2 = dgr2.KucukResim;
            return View("HaberGetir", flm);
        }
        public ActionResult HaberGuncelle(Haber k)
        {
            if (!ModelState.IsValid)
            {
                return View("HaberGetir");
            }
            try
            {
                if (Request.Files.Count > 0)
                {
                    string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);
                    string yol = "~/images/" + dosyaadi + uzanti;
                    Request.Files[0].SaveAs(Server.MapPath(yol));
                    k.KucukResim = "/images/" + dosyaadi + uzanti;
                }
            }
            catch (System.IO.DirectoryNotFoundException)
            {
                var f = c.Habers.Find(k.id);
                f.Title = k.Title;
                f.Metatitle = k.Metatitle;
                f.Shortinfo = k.Shortinfo;
                f.İcerik = k.İcerik;
                f.PostedDate = k.PostedDate;
                f.Active = k.Active;
                f.KucukResim = k.KucukResim;

                c.SaveChanges();
                return RedirectToAction("Index2");
            }
            var fm = c.Habers.Find(k.id);
            fm.Title = k.Title;
            fm.Metatitle = k.Metatitle;
            fm.Shortinfo = k.Shortinfo;
            fm.İcerik = k.İcerik;
            fm.PostedDate = k.PostedDate;
            fm.Active = k.Active;
            fm.KucukResim = k.KucukResim;
            c.SaveChanges();
            return RedirectToAction("Index2");

        }

    }
}

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Haber/HaberGetir.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Haber

@{
    ViewBag.Title = "HaberGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("HaberGuncelle", "Haber", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.HiddenFor(x => x.id)

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Meta Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Metatitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Metatitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Küçük Resim", htmlAttributes: new { @class = "control-label col-md-2" })

        <div class="col-md-10">
            <input type="file" name="KucukResim" />
            <input type="text" name="KucukResim" value="@ViewBag.dgr2" class="form-control" style="width:185px;" readonly />
        </div>
    </div>


    <div class="form-group">
        @Html.Label("Kısa Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Shortinfo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Shortinfo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("İçerik", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-10">
            @Html.TextAreaFor(m => m.İcerik, new { @id = "summernote" })

        </div>


    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostedDate, new
            {
                htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.ToString("dd/MM/yyyy") }
       })
            @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Güncelle" class="btn btn-default" />
        </div>
    </div>
</div>
}



<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>


<!-- include libraries(jQuery, bootstrap) -->
@*<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@

<script>
    $('#summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 500,

        //callbacks: {
        //    onImageUpload: function (files) {
        //        for (var i = 0; i < files.length; i++) {

        //            uploadImage(files[i]);
        //        }
        //    }
        //},
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });
    function uploadImage(file) {
        var formData = new FormData();
        formData.append("uploadedFiles", file);
        $.ajax({
            data: formData,
            type: "POST",
            url: '/Post/UploadFile',
            cache: false,
            contentType: false,

            processData: false,
            success: function (FileUrl) {
                alert(FileUrl);
                var imgNode = document.createElement('img');
                imgNode.src = FileUrl;
                $('#summernote').summernote('insertNode', imgNode);
            },
            error: function (data) {
                alert(data.responseText);
            }
        });
    }



</script>



SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Haber/Index.cshtml
@using SinemaBiletOtomasyonu.Models.Siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Haber>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AnaLayout.cshtml";
}

@using (Html.BeginForm("Index", "Haber", FormMethod.Get))
{
    <div class="container">
        <h2>Bu Hafta Neler Oldu</h2>

        <div class="row">
            @foreach (var k in Model)
            {
                <div class="col-md-3">
                    <div class="thumbnail">
                        <a href="/Detay/Index/@k.id" target="_blank">
                            <img src="~/images/@k.KucukResim" alt="Lights" style="width:100%">
                            <div class="caption">
                                <p>@k.Title</p>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>

    </div>
}
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Haber/Index2.cshtml
@using SinemaBiletOtomasyonu.Models.Siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Haber>

@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Index2", "Haber", FormMethod.Get))
{

    <b> Arama Seçeneği: </b>@Html.RadioButton("option", "id") <text>Haber id</text>
    @Html.RadioButton("option", "PostedDate") <text> Post Tarihi </text>
    @Html.RadioButton("option", "Title") <text> Başlık </text>
    @Html.RadioButton("option", "Tumu") <text>Tümü</text>
    @Html.TextBox("search")
    <input type="submit"
           name="submit"
           value="Search" />

    <table class="table table-bordered" style="margin:20px">

        <tr>
            <th>Haber ID</th>
            <th>Başlık</th>
            <th>Meta Başlık</th>
            <th>Kısa Açıklama</th>

            <th>Post Tarihi</th>

            <th>Küçük Resim</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Detay</th>

        </tr>

        @foreach (var k in Model)
        {

            <tr>
                <td>
                    @k.id
                </td>
                <td>
                    @k.Title
                </td>
                <td>
                    @k.Metatitle
                </td>
                <td>
                    @k.Shortinfo.Substring(0, 10)
                </td>

                <td>
                    @k.PostedDate
                </td>



                <td>
                    <img src="~/images/@k.KucukResim" width="50px" height="50px" />
                </td>
                <td> <a href="/Haber/HaberSil/@k.id" class="btn btn-danger"><font color="white">Sil</font></a></td>
                <td> <a href="/Haber/HaberGetir/@k.id" class="btn btn-warning"><font color="white">Güncelle</font></a></td>
                <td> <a href="/Detay/Index/@k.id" class="btn btn-primary"><font color="white">Detay</font></a></td>

            </tr>
        }
    </table>
    <a href="/Haber/YeniHaber" class="btn btn-info">Haber Ekle</a>
    <br />
    <br />
}
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index2", new { page }))

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Haber/YeniHaber.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Haber
@{
    ViewBag.Title = "YeniHaber";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>YeniHaber</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Meta Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Metatitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Metatitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Küçük Resim", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="KucukResim" />
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Kısa Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Shortinfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Shortinfo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("İçerik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-10">
                <textarea id="summernote" name="İcerik"></textarea>
            </div>
            

        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostedDate, new
                {
                    htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.ToString("dd/MM/yyyy") }
           })
                @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>


<!-- include libraries(jQuery, bootstrap) -->
@*<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@

<script>
    $('#summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 500,

        //callbacks: {
        //    onImageUpload: function (files) {
        //        for (var i = 0; i < files.length; i++) {

        //            uploadImage(files[i]);
        //        }
        //    }
        //},
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });
    function uploadImage(file) {
        var formData = new FormData();
        formData.append("uploadedFiles", file);
        $.ajax({
            data: formData,
            type: "POST",
            url: '/Post/UploadFile',
            cache: false,
            contentType: false,

            processData: false,
            success: function (FileUrl) {
                alert(FileUrl);
                var imgNode = document.createElement('img');
                imgNode.src = FileUrl;
                $('#summernote').summernote('insertNode', imgNode);
            },
            error: function (data) {
                alert(data.responseText);
            }
        });
    }



</script>

SinemaBiletOtomasyonu/SinemaBiletOtomasyonu/Views/Haber/haberekle.cshtml
@model SinemaBiletOtomasyonu.Models.Siniflar.Haber
@{
    
    Layout = "null";
}

<h2>YeniHaber</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Meta Başlık", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Metatitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Metatitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Küçük Resim", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="KucukResim" />
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Kısa Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Shortinfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Shortinfo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("İçerik", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-10">
                <textarea id="summernote" name="İcerik"></textarea>
            </div>


        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.İcerik, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.İcerik, new { htmlAttributes = new { id = "summernote", name="editordata" } })
                    @Html.ValidationMessageFor(model => model.İcerik, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostedDate, new
                {
                    htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.ToString("dd/MM/yyyy") }
           })
                @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<!-- include libraries(jQuery, bootstrap) -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<script>
    $('#summernote').summernote({
        placeholder: 'Hello stand alone ui',
        tabsize: 2,
        height: 500,

        //callbacks: {
        //    onImageUpload: function (files) {
        //        for (var i = 0; i < files.length; i++) {

        //            uploadImage(files[i]);
        //        }
        //    }
        //},
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });

    function uploadImage(file) {
        var formData = new FormData();
        formData.append("uploadedFiles", file);
        $.ajax({
            data: formData,
            type: "POST",
            url: '/Post/UploadFile',
            cache: false,
            contentType: false,

            processData: false,
            success: function (FileUrl) {
                alert(FileUrl);
                var imgNode = document.createElement('img');
                imgNode.src = FileUrl;
                $('#summernote').summernote('insertNode', imgNode);
            },
            error: function (data) {
                alert(data.responseText);
            }
        });
    }


</script>